export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_MODEL_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const CHECKOUT_OPEN_MODAL = 'CHECKOUT_OPEN_MODAL';
export const CHECKOUT_CLOSE_MODAL = 'CHECKOUT_CLOSE_MODAL';
export const PURCHASE_MODEL_START = 'PURCHASE_MODEL_START';
export const PURCHASE_MODEL_SUCCESS = 'PURCHASE_MODEL_SUCCESS';
export const PURCHASE_MODEL_FAIL = 'PURCHASE_MODEL_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const MODEL_FINISHED_LOADING = 'MODEL_FINISHED_LOADING';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_OPEN_MODAL = 'AUTH_OPEN_MODAL';
export const AUTH_CLOSE_MODAL = 'AUTH_CLOSE_MODAL';


export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const LOAD_CART = 'LOAD_CART';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_CART = 'UPDATE_CART';
export const FINISHED_ADD = 'FINISHED_ADD';
export const ADD_IN_PROGRESS = 'ADD_IN_PROGRSS';
export const RESET_CART = 'RESET_CART';
export const ENTER_CHECKOUT = 'ENTER_CHECKOUT';
export const EXIT_CHECKOUT = 'EXIT_CHECKOUT';

export const CLIENT_CREATED = 'CLIENT_CREATED';
export const CHECKOUT_FOUND = 'CHECKOUT_FOUND';
export const SHOP_FOUND = 'SHOP_FOUND';

export const OPEN_SAVED_MODAL = 'OPEN_SAVED_MODAL';
export const CLOSE_SAVED_MODAL = 'CLOSE_SAVED_MODAL';
export const OPEN_NAME_MODAL = 'OPEN_NAME_MODAL';
export const CLOSE_NAME_MODAL = 'CLOSE_NAME_MODAL';
export const OPEN_DELETE_MODAL = 'OPEN_DELETE_MODAL';
export const CLOSE_DELETE_MODAL = 'CLOSE_DELETE_MODAL';
export const ADD_SAVED_MODELS = 'ADD_SAVED_MODELS';
export const REMOVE_SAVED_MODEL = 'REMOVE_SAVED_MODEL';
export const UPDATE_SAVED_MODEL = 'UPDATE_SAVED_MODEL';
export const SELECT_MODEL = 'SELECT_MODAL';
export const SAVE_IN_PROGRESS = 'SAVE_IN_PROGRESS';
export const SAVE_COMPLETE = 'SAVE_COMPLETE';

