export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_MODEL_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const CHECKOUT_OPEN_MODAL = 'CHECKOUT_OPEN_MODAL';
export const CHECKOUT_CLOSE_MODAL = 'CHECKOUT_CLOSE_MODAL';
export const PURCHASE_MODEL_START = 'PURCHASE_MODEL_START';
export const PURCHASE_MODEL_SUCCESS = 'PURCHASE_MODEL_SUCCESS';
export const PURCHASE_MODEL_FAIL = 'PURCHASE_MODEL_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const MODEL_FINISHED_LOADING = 'MODEL_FINISHED_LOADING';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_OPEN_MODAL = 'AUTH_OPEN_MODAL';
export const AUTH_CLOSE_MODAL = 'AUTH_CLOSE_MODAL';
